# This script defines the different stages of a CI job to test my DC motor controller using a CICD framework
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.


stages:          # List of stages for jobs, and their order of execution
  - check
  - test
  - codeGen
  - webviewGen
  - simpleAppGen
  - saveArtifacts

variables:
  ARTIFACTS_DOWNLOAD_PATH: "C:/Users/$GITLAB_USER_LOGIN/Downloads"


mdlAdvisor-checks-job:       # This job runs in the model checks stage
    stage: check
    tags:
      - on-prem
    script:
      - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); runProjectChecks;"
    artifacts:
      when: always
      paths:
        - GeneratedArtifacts/CheckResults/

unit-SlTest-job:   # This job runs in the test stage.
    stage: test 
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); results = runProjectTests; assertSuccess(results);"
    artifacts:
      when: always
      paths:
        - GeneratedArtifacts/TestResults/
      reports:
        junit: GeneratedArtifacts/TestResults/*.xml

codeGen-job:      # This job runs the codeGen stage.
    stage: codeGen  
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genCCode;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/CodeGen/

webviewGen-job:      # This job runs generated webviews of models
    stage: webviewGen  
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genWebView;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/Webviews

genSimpleApp:
    stage: simpleAppGen
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genSimpleApp;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/DeployableApps

# a stage to assert that all stages in this child pipeline have passed successfully.
artifactGen:      # Final Stage to alert users this job is done.
    stage: saveArtifacts
    tags:
        - on-prem
    script:
        - echo "Job Done!"