# This script defines the different stages of a CI job to test my DC motor controller using a CICD framework
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.


stages:          # List of stages for jobs, and their order of execution
  - diffDoc
  - check
  - test
  - codeGen
  - webviewGen
  - simpleAppGen
  - cleanUpandClose

variables:
  ARTIFACTS_DOWNLOAD_PATH: "C:/Users/$GITLAB_USER_LOGIN/Downloads"

diffDoc-job:       # This job runs in the model checks stage
    stage: diffDoc
    tags:
      - on-prem
    script:
      - apt-get install -y git                       # This command used for installing Git
      - diffM=$(git diff --name-only --diff-filter=M $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA -- **/*.slx)
      - diffA=$(git diff --name-only --diff-filter=A $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA -- **/*.slx)
      - diffD=$(git diff --name-only --diff-filter=D $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA -- **/*.slx)
      - echo "::set-output name=diffA::$diffA"
      - echo "::set-output name=diffM::$diffM"
      - echo "::set-output name=diffM::$diffD"
      - echo "Modified SLX files:"
      - echo "$diffM"
      - echo "Added SLX files:"
      - echo "$diffA"
      - echo "Deleted SLX files:"
      - echo "$diffD"
      - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); lastpush = "$CI_COMMIT_BEFORE_SHA"; changeList = "$diffM"; diff_push(changeList,lastpush);"
    artifacts:
      when: always
      paths:
        - GeneratedArtifacts/DiffReports/

mdlAdvisor-checks-job:       # This job runs in the model checks stage
    stage: check
    tags:
      - on-prem
    script:
      - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); runProjectChecks;"
    artifacts:
      when: always
      paths:
        - GeneratedArtifacts/CheckResults/

unit-SlTest-job:   # This job runs in the test stage.
    stage: test 
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); results = runProjectTests; assertSuccess(results);"
    artifacts:
      when: always
      paths:
        - GeneratedArtifacts/TestResults/
      reports:
        junit: GeneratedArtifacts/TestResults/*.xml

codeGen-job:      # This job runs the codeGen stage.
    stage: codeGen  
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genCCode;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/CodeGen/

webviewGen-job:      # This job runs generated webviews of models
    stage: webviewGen  
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genWebView;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/Webviews

genSimpleApp:
    stage: simpleAppGen
    tags:
        - on-prem
    script:
        - mw -using R2022b matlab -nodesktop -batch "openProject('DCMotorCtrl.prj'); genSimpleApp;"
    artifacts:
        when: always
        paths:
            - GeneratedArtifacts/DeployableApps

# a stage to assert that all stages in this child pipeline have passed successfully.
artifactGen:      # Final Stage to alert users this job is done.
    stage: cleanUpandClose
    tags:
        - on-prem
    script:
        - echo "Job Done!"